package template

import (
	"io"
	gotemplate "text/template"
	"time"
)

// the {{ tick }} stuff is because this https://github.com/golang/go/issues/18221#issuecomment-394255883

const airportDataTemplate string = `package {{ .Package }}

// this file was generated by the go-sfomuseum-airports-tools package on {{ .LastUpdate }}
{{ $tick := "` + "`" + `" }}
const AirportData string = {{ $tick }}{{ .Data }}{{ $tick }}
`

type AirportDataVars struct {
	Package    string
	Data       string
	LastUpdate string
}

func RenderAirportData(wr io.Writer, vars *AirportDataVars) error {

	now := time.Now()

	vars.LastUpdate = now.Format(time.RFC3339)

	t := gotemplate.New("data")
	t, err := t.Parse(airportDataTemplate)

	if err != nil {
		return err
	}

	return t.Execute(wr, vars)
}
